[theme]
primaryColor = "#1E88E5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false  # Changed to false to allow CORS
enableCORS = true  # Enable CORS explicitly